In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("D:/R Programming/Data Files/4. ST Academy - SVM resource files/Movie_regression.csv")

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Missing value Imputation

In [5]:
df["Time_taken"].mean()

157.39149797570855

In [6]:
df["Time_taken"].fillna(value=df["Time_taken"].mean(),inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [8]:
df=pd.get_dummies(df,columns=['3D_available','Genre'],drop_first=True)

In [9]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

### X-Y split

In [10]:
x=df.loc[:,df.columns!='Collection']
type(x)

pandas.core.frame.DataFrame

In [11]:
x.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  3D_available_YES  Genre_Comedy  Genre_Drama  \
0              23            494                 1             0            0   
1              42            462                 0             0            1   
2              38            458                 0             1            0   
3              45            472                 1             0            1   
4              55            395                 0             0            1   

   Genre_Thriller  
0               1  
1               0  
2               0  
3               0  
4               0

In [12]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  Time_taken           506 non-null    float64
 12  Twitter_hastags      506 non-null    float64
 13  Avg_age_actors       506 non-null    int64  
 14  Num_multiplex        506 non-null    int64  
 15  3D_available_YES     506 non-null    uin

In [13]:
x.shape

(506, 19)

In [14]:
y=df['Collection']
type(y)

pandas.core.series.Series

### Test-Train Split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [17]:
x_train.shape

(404, 19)

In [18]:
x_test.shape

(102, 19)

### Standardizing the data, convert mean and variance of all the variables as either 0  and 1 respectively

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc=StandardScaler().fit(x_train)

In [21]:
x_train_std=sc.transform(x_train)

In [22]:
x_test_std=sc.transform(x_test)

In [23]:
x_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training Regression Tree

In [24]:
from sklearn.svm import SVR
svr=SVR(kernel='linear',C=1000)

In [26]:
svr.fit(x_train_std,y_train)

SVR(C=1000, kernel='linear')

### Predicting values using trained model

In [27]:
y_test_pred=svr.predict(x_test_std)
y_train_pred=svr.predict(x_train_std)

In [30]:
y_test_pred

array([54170.53503625, 42284.13073447, 47467.48411681, 18129.17355968,
       48399.2694108 , 39866.86998057, 34007.32532044, 43289.77824001,
       30366.10675075, 47064.86893308, 12791.33749785, 38408.82653373,
       37559.85784034,  8779.61135966, 66820.90169749, 61934.22332501,
       38795.59236698, 65521.75338819, 57150.63894057, 43345.30648075,
       53845.74438999, 39163.9161095 , 41674.15698489, 58329.2948265 ,
       42884.07327353, 13145.18400653, 40922.72188255, 29718.76094569,
       74630.97971381, 44573.11287423, 36854.7122831 , 37424.55686816,
       37582.94829537, 40845.85075693, 52096.63581819, 35540.25290306,
       25313.83859774, 36522.56259703, 36623.75409555, 35831.61173002,
       47370.51557929, 45957.66677543, 44656.54171505, 27680.22280557,
       50609.67508545, 46713.98056409, 33197.61112633, 40047.74770769,
       15830.8986982 , 51791.84658664, 41241.55116877, 39132.63366916,
       47511.3684718 , 67543.6845176 , 25372.80865713, 41659.98849411,
      

### model performance

In [31]:
from sklearn.metrics import mean_squared_error,r2_score

In [32]:
mean_squared_error(y_test,y_test_pred)

160153135.39405018

In [34]:
r2_score(y_train,y_train_pred)

0.7124450931551785

In [35]:
r2_score(y_test,y_test_pred)

0.5025135728682528

# Classificaion Tree

In [37]:
df1=pd.read_csv("D:/R Programming\Data Files/4. ST Academy - SVM resource files/Movie_classification.csv")

In [38]:
df1.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [40]:
df1['Time_taken'].mean()

157.39149797570855

In [42]:
df1['Time_taken'].fillna(value=df1['Time_taken'].mean(),inplace=True)

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

In [45]:
df1=pd.get_dummies(df1,columns=['3D_available','Genre'],drop_first=True)

In [46]:
df1.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

## X-Y Split

In [49]:
x=df1.loc[:,df1.columns!='Start_Tech_Oscar']
type(x)

pandas.core.frame.DataFrame

In [52]:
y=df1['Start_Tech_Oscar']
type(y)

pandas.core.series.Series

### Test_train_split

In [53]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0,test_size=0.2)

In [59]:
x_test.shape

(102, 20)

In [60]:
x_train.shape

(404, 20)

### Standardizing data

In [61]:
from sklearn.preprocessing import StandardScaler

In [63]:
sc=StandardScaler().fit(x_train)

In [64]:
x_train_std=sc.transform(x_train)

In [65]:
x_test_std=sc.transform(x_test)

In [66]:
x_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

### Training SVM

In [67]:
from sklearn import svm

In [68]:
clf_svm_1=svm.SVC(kernel='linear',C=0.01)

In [69]:
clf_svm_1.fit(x_train_std,y_train)

SVC(C=0.01, kernel='linear')

In [70]:
y_train_pred=clf_svm_1.predict(x_train_std)
y_test_pred=clf_svm_1.predict(x_test_std)

In [72]:
y_train_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

#### Model performance

In [73]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [74]:
confusion_matrix(y_test,y_test_pred)

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [75]:
accuracy_score(y_test,y_test_pred)

0.6274509803921569

In [76]:
clf_svm_1.n_support_

array([186, 189])

### Hyper parameter tuning

In [77]:
from sklearn.model_selection import GridSearchCV 
# To avoid changing C

In [95]:
params={'C':(0.001,0.005,0.01,0.05,0.1,1,5,10,100,500,1000)}

In [96]:
clf_svm_1=svm.SVC(kernel='linear')

In [97]:
svm_grid_lin=GridSearchCV(clf_svm_1,params,n_jobs=-1, 
                         cv=10,verbose=1,scoring='accuracy')

In [98]:
svm_grid_lin.fit(x_train_std,y_train)

Fitting 10 folds for each of 11 candidates, totalling 110 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 1, 5, 10, 100,
                               500, 1000)},
             scoring='accuracy', verbose=1)

In [99]:
svm_grid_lin.best_params_

{'C': 0.1}

In [100]:
linsvm_clf=svm_grid_lin.best_estimator_

In [102]:
accuracy_score(y_test,linsvm_clf.predict(x_test_std))

0.5980392156862745

### Polynomial

In [104]:
clf_svm_p3=svm.SVC(kernel='poly',degree=2,C=0.1)
clf_svm_p3.fit(x_train_std,y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [105]:
y_train_pred=clf_svm_p3.predict(x_train_std)
y_test_pred=clf_svm_p3.predict(x_test_std)

In [107]:
accuracy_score(y_test,y_test_pred)

0.5588235294117647

In [109]:
clf_svm_p3.n_support_

array([185, 194])

### Radial Kernel

In [111]:
clf_svm_r=svm.SVC(kernel='rbf',gamma=0.5,C=10)
clf_svm_r.fit(x_train_std,y_train)

SVC(C=10, gamma=0.5)

In [112]:
y_train_pred=clf_svm_r.predict(x_train_std)
y_test_pred=clf_svm_r.predict(x_test_std)

In [113]:
accuracy_score(y_test,y_test_pred)

0.6176470588235294

In [115]:
clf_svm_r.n_support_

array([186, 218])

### Radial Grid

In [116]:
params={'C':(0.01,0.05,0.1,0.5,1,5,10,50),'gamma':(0.001,0.01,0.1,0.5,1)}

In [117]:
clf_svm_r=svm.SVC(kernel='rbf')

In [118]:
svm_grid_rad=GridSearchCV(clf_svm_r,params,n_jobs=-1,cv=3,verbose=1,scoring='accuracy')

In [120]:
svm_grid_rad.fit(x_train_std,y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             scoring='accuracy', verbose=1)

In [121]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [122]:
radsvm_clf=svm_grid_rad.best_estimator_

In [123]:
accuracy_score(y_test,radsvm_clf.predict(x_test_std))

0.6176470588235294